[project]
name = "seat-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.12",
    "botocore>=1.43.12",
    "fastapi>=0.136.0",
    "jinja2>=3.1.6",
    "mangum==0.21.0",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.14.0",
    "pyjwt>=2.12.1",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.26",
    "requests>=2.33.1",
    "structlog>=24.0.0",
    "tenacity>=9.0.0",
    "uvicorn>=0.44.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]

[tool.ruff.lint]
ignore = ['DTZ011', 'DTZ001', 'DTZ901', 'B008', 'RUF013', 'G201', 'BLE001', 'SIM101', 'FLY002', 'F821', 'C408', 'S110', 'PIE794', 'F811', 'PYI034', 'RUF012', 'SIM117']
