import { Ban, ChevronLeft, ChevronRight } from "lucide-react";
import type { BlockedSeat } from "../types/blockedSeats.types";
import { STATUS_LABELS, STATUS_STYLES, TYPE_LABELS, TYPE_STYLES } from "../utils/constants";

const displayDate = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));
interface Props { title: string; rows: BlockedSeat[]; total: number; page: number; totalPages: number; loading: boolean; onPageChange: (page: number) => void; onCancel: (row: BlockedSeat) => void }
export default function BlockedSeatsTable({ title, rows, total, page, totalPages, loading, onPageChange, onCancel }: Props) {
  const headings = ["Seat", "Location", "Block Period", "Type", "Reason", "Status", "Blocked By", "Actions"];
  const start = total ? (page - 1) * 20 + 1 : 0;
  return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><h2 className="border-b border-slate-200 px-4 py-3 text-base font-semibold text-slate-900">{title}</h2><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-slate-50 text-[11px] font-semibold text-slate-600"><tr>{headings.map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{!loading && rows.map((row) => <tr key={row.block_id} className="text-slate-600 hover:bg-slate-50/70"><td className="px-4 py-3 font-semibold text-slate-800">{row.seat_code}</td><td className="whitespace-nowrap px-4 py-3">{row.site_name} · {row.building_name} · {row.floor_name}</td><td className="whitespace-nowrap px-4 py-3">{displayDate(row.blocked_from)} – {displayDate(row.blocked_to)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-medium ${TYPE_STYLES[row.block_type]}`}>{TYPE_LABELS[row.block_type]}</span></td><td className="max-w-[190px] px-4 py-3">{row.reason}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-medium ${STATUS_STYLES[row.display_status]}`}>{STATUS_LABELS[row.display_status]}</span></td><td className="whitespace-nowrap px-4 py-3">{row.blocked_by.name ?? "—"}</td><td className="px-4 py-3">{row.display_status === "EXPIRED" ? <span className="text-slate-300">—</span> : <button onClick={() => onCancel(row)} title="Unblock seat" aria-label={`Unblock seat ${row.seat_code}`} className="rounded p-1 text-slate-500 hover:bg-red-50 hover:text-red-600"><Ban size={16}/></button>}</td></tr>)}</tbody></table>{loading ? <p className="py-12 text-center text-sm text-slate-400">Loading blocked seats…</p> : !rows.length && <p className="py-12 text-center text-sm text-slate-400">No blocked seats match the selected criteria.</p>}</div><footer className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500"><span>Showing {start}{total ? `–${Math.min(start + rows.length - 1, total)}` : ""} of {total}</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => onPageChange(page - 1)} className="flex h-8 w-8 items-center justify-center rounded-md border disabled:opacity-40"><ChevronLeft size={15}/></button><button className="h-8 min-w-8 rounded-md border border-violet-500 bg-violet-50 font-semibold text-violet-700">{page}</button><button disabled={page >= totalPages} onClick={() => onPageChange(page + 1)} className="flex h-8 w-8 items-center justify-center rounded-md border disabled:opacity-40"><ChevronRight size={15}/></button></div></footer></section>;
}
